export * from './category';
export * from './destination';
// export * from './hotel';
export * from './label';
export * from './landing';
export * from './menu';
// export * from './page';
export * from './promotion';
export * from './region';
// export * from './search-result';
export * from './slug';
export * from './tag';
export * from './test';
export * from './user';
export * from './wishlist';
