export * from './label';
// export * from './destination';
// export * from './hotel';
// export * from './landing';
// export * from './search-result';
// export * from './last-views';
// export * from './menu';
// export * from './order';
// export * from './page';
// export * from './promotion';
// export * from './province';
// export * from './slug';
// export * from './tag';
// export * from './test';
// export * from './user';
// export * from './wishlist';
