import { County } from '../models/data.service';

export const province: County[] = [
	{ id: 'AG', value: 'Agrigento' },
	{ id: 'AL', value: 'Alessandria' },
	{ id: 'AN', value: 'Ancona' },
	{ id: 'AO', value: 'Valle d\'Aosta' },
	{ id: 'AR', value: 'Arezzo' },
	{ id: 'AP', value: 'Ascoli Piceno' },
	{ id: 'AT', value: 'Asti' },
	{ id: 'AV', value: 'Avellino' },
	{ id: 'BT', value: 'Barletta-Andria-Trani' },
	{ id: 'BL', value: 'Belluno' },
	{ id: 'BN', value: 'Benevento' },
	{ id: 'BG', value: 'Bergamo' },
	{ id: 'BI', value: 'Biella' },
	{ id: 'BZ', value: 'Bolzano' },
	{ id: 'BS', value: 'Brescia' },
	{ id: 'BR', value: 'Brindisi' },
	{ id: 'CL', value: 'Caltanissetta' },
	{ id: 'CB', value: 'Campobasso' },
	{ id: 'CE', value: 'Caserta' },
	{ id: 'CZ', value: 'Catanzaro' },
	{ id: 'CH', value: 'Chieti' },
	{ id: 'CO', value: 'Como' },
	{ id: 'CS', value: 'Cosenza' },
	{ id: 'CR', value: 'Cremona' },
	{ id: 'KR', value: 'Crotone' },
	{ id: 'CN', value: 'Cuneo' },
	{ id: 'EN', value: 'Enna' },
	{ id: 'FM', value: 'Fermo' },
	{ id: 'FE', value: 'Ferrara' },
	{ id: 'FG', value: 'Foggia' },
	{ id: 'FC', value: 'Forlì-Cesena' },
	{ id: 'FR', value: 'Frosinone' },
	{ id: 'GO', value: 'Gorizia' },
	{ id: 'GR', value: 'Grosseto' },
	{ id: 'IM', value: 'Imperia' },
	{ id: 'IS', value: 'Isernia' },
	{ id: 'SP', value: 'La Spezia' },
	{ id: 'AQ', value: 'L\'Aquila' },
	{ id: 'LT', value: 'Latina' },
	{ id: 'LE', value: 'Lecce' },
	{ id: 'LC', value: 'Lecco' },
	{ id: 'LI', value: 'Livorno' },
	{ id: 'LO', value: 'Lodi' },
	{ id: 'LU', value: 'Lucca' },
	{ id: 'MC', value: 'Macerata' },
	{ id: 'MN', value: 'Mantova' },
	{ id: 'MS', value: 'Massa-Carrara' },
	{ id: 'MT', value: 'Matera' },
	{ id: 'ME', value: 'Messina' },
	{ id: 'MB', value: 'Monza e Brianza' },
	{ id: 'MO', value: 'Modena' },
	{ id: 'NO', value: 'Novara' },
	{ id: 'NU', value: 'Nuoro' },
	{ id: 'OR', value: 'Oristano' },
	{ id: 'PD', value: 'Padova' },
	{ id: 'PR', value: 'Parma' },
	{ id: 'PV', value: 'Pavia' },
	{ id: 'PG', value: 'Perugia' },
	{ id: 'PU', value: 'Pesaro e Urbino' },
	{ id: 'PE', value: 'Pescara' },
	{ id: 'PC', value: 'Piacenza' },
	{ id: 'PI', value: 'Pisa' },
	{ id: 'PT', value: 'Pistoia' },
	{ id: 'PN', value: 'Pordenone' },
	{ id: 'PZ', value: 'Potenza' },
	{ id: 'PO', value: 'Prato' },
	{ id: 'RG', value: 'Ragusa' },
	{ id: 'RA', value: 'Ravenna' },
	{ id: 'RE', value: 'Reggio Emilia' },
	{ id: 'RI', value: 'Rieti' },
	{ id: 'RN', value: 'Rimini' },
	{ id: 'RO', value: 'Rovigo' },
	{ id: 'SA', value: 'Salerno' },
	{ id: 'SS', value: 'Sassari' },
	{ id: 'SV', value: 'Savona' },
	{ id: 'SI', value: 'Siena' },
	{ id: 'SR', value: 'Siracusa' },
	{ id: 'SO', value: 'Sondrio' },
	{ id: 'TA', value: 'Taranto' },
	{ id: 'TE', value: 'Teramo' },
	{ id: 'TR', value: 'Terni' },
	{ id: 'TP', value: 'Trapani' },
	{ id: 'TN', value: 'Trento' },
	{ id: 'TV', value: 'Treviso' },
	{ id: 'TS', value: 'Trieste' },
	{ id: 'UD', value: 'Udine' },
	{ id: 'VA', value: 'Varese' },
	{ id: 'VB', value: 'Verbano-Cusio-Ossola' },
	{ id: 'VC', value: 'Vercelli' },
	{ id: 'VR', value: 'Verona' },
	{ id: 'VV', value: 'Vibo Valentia' },
	{ id: 'VI', value: 'Vicenza' },
	{ id: 'VT', value: 'Viterbo' }

];


