import { Tag } from '../models/tag';

export const tag: Tag[] = [{
	abstract: 'Centro benessere',
	category: -1,
	icon: '104_37_ico-benessere.png',
	id: 37,
	name: 'Centro benessere',
	slug: ''
}, {
	abstract: 'Servizio spiaggia',
	category: -1,
	icon: '104_38_ico-spiaggia.png',
	id: 38,
	name: 'Servizio spiaggia',
	slug: ''
}, {
	abstract: 'Skipass',
	category: -1,
	icon: '104_39_ico-skipass.png',
	id: 39,
	name: 'Skipass',
	slug: ''
}, {
	abstract: '',
	category: -1,
	icon: '104_60_ico-traghettoincluso.png',
	id: 60,
	name: 'Traghetto incluso',
	slug: ''
}, {
	abstract: '',
	category: -1,
	icon: '104_61_ico-voloincluso.png',
	id: 61,
	name: 'Volo incluso',
	slug: ''
}, {
	abstract: 'Buono spesa',
	category: -1,
	icon: '104_80_buono_spesa.png',
	id: 80,
	name: 'Buono spesa',
	slug: ''
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 1,
	name: 'Mare Italia',
	slug: 'destinazioni/mare-italia'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 3,
	name: 'Sardegna + traghetto',
	slug: 'destinazioni/sardegna-traghetto'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 4,
	name: 'Montagna',
	slug: 'destinazioni/montagna'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 5,
	name: 'Crociere',
	slug: 'destinazioni/crociera'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 42,
	name: 'Terme & benessere',
	slug: 'destinazioni/terme-benessere'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 40,
	name: 'Lago',
	slug: 'destinazioni/lago'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 75,
	name: 'Campagna',
	slug: 'destinazioni/campagna'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 43,
	name: 'Vacanze a tema',
	slug: 'vacanze_a_tema'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 2,
	name: 'Mare estero',
	slug: 'destinazioni/mare-estero'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 41,
	name: 'Città',
	slug: 'destinazioni/città'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 76,
	name: 'Residence & Appartamenti',
	slug: 'vacanze_residence_appartamenti'
}, {
	abstract: '',
	category: 0,
	icon: null,
	id: 44,
	name: 'Tour',
	slug: 'destinazioni/tour-organizzati'
}, {
	abstract: '',
	category: 1,
	icon: '104_63_novita_vuoto.png',
	id: 63,
	name: 'Novità',
	slug: 'novità'
}, {
	abstract: '',
	category: 1,
	icon: '104_8_ico-bimbigratis.png',
	id: 8,
	name: 'Bimbo gratis',
	slug: 'destinazioni/bimbo-gratis'
}, {
	abstract: '',
	category: 1,
	icon: '104_9_ico-amici4zampe.png',
	id: 9,
	name: 'Amici 4 zampe',
	slug: 'destinazioni/amici-4-zampe'
}, {
	abstract: '',
	category: 1,
	icon: '',
	id: 11,
	name: 'Prenota prima',
	slug: 'destinazioni/prenota-prima'
}, {
	abstract: '',
	category: 1,
	icon: '104_56_ico-last-minute.png',
	id: 56,
	name: 'Last minute',
	slug: 'destinazioni/last-minute'
}, {
	abstract: 'Abruzzo',
	category: 2,
	icon: null,
	id: 12,
	name: 'Abruzzo',
	slug: 'destinazioni/abruzzo'
}, {
	abstract: 'Basilicata',
	category: 2,
	icon: null,
	id: 14,
	name: 'Basilicata',
	slug: 'destinazioni/basilicata'
}, {
	abstract: 'Calabria',
	category: 2,
	icon: null,
	id: 15,
	name: 'Calabria',
	slug: 'destinazioni/calabria'
}, {
	abstract: 'Campania',
	category: 2,
	icon: null,
	id: 16,
	name: 'Campania',
	slug: 'destinazioni/campania'
}, {
	abstract: 'Emilia Romagna',
	category: 2,
	icon: null,
	id: 17,
	name: 'Emilia Romagna',
	slug: 'destinazioni/emilia-romagna'
}, {
	abstract: 'Friuli Venezia Giulia',
	category: 2,
	icon: null,
	id: 18,
	name: 'Friuli Venezia Giulia',
	slug: 'destinazioni/friuli-venezia-giulia'
}, {
	abstract: 'Lazio',
	category: 2,
	icon: null,
	id: 19,
	name: 'Lazio',
	slug: 'destinazioni/lazio'
}, {
	abstract: 'Liguria',
	category: 2,
	icon: null,
	id: 20,
	name: 'Liguria',
	slug: 'destinazioni/liguria'
}, {
	abstract: 'Lombardia',
	category: 2,
	icon: null,
	id: 21,
	name: 'Lombardia',
	slug: 'destinazioni/lombardia'
}, {
	abstract: 'Marche',
	category: 2,
	icon: null,
	id: 22,
	name: 'Marche',
	slug: 'destinazioni/marche'
}, {
	abstract: 'Molise',
	category: 2,
	icon: null,
	id: 47,
	name: 'Molise',
	slug: 'destinazioni/molise'
}, {
	abstract: 'Piemonte',
	category: 2,
	icon: null,
	id: 23,
	name: 'Piemonte',
	slug: 'destinazioni/piemonte'
}, {
	abstract: 'Puglia',
	category: 2,
	icon: null,
	id: 24,
	name: 'Puglia',
	slug: 'destinazioni/puglia'
}, {
	abstract: 'Sardegna',
	category: 2,
	icon: null,
	id: 25,
	name: 'Sardegna',
	slug: 'destinazioni/sardegna'
}, {
	abstract: 'Sicilia',
	category: 2,
	icon: null,
	id: 26,
	name: 'Sicilia',
	slug: 'destinazioni/sicilia'
}, {
	abstract: 'Toscana',
	category: 2,
	icon: null,
	id: 27,
	name: 'Toscana',
	slug: 'destinazioni/toscana'
}, {
	abstract: 'Trentino Alto Adige',
	category: 2,
	icon: null,
	id: 28,
	name: 'Trentino Alto Adige',
	slug: 'destinazioni/trentino-alto-adige'
}, {
	abstract: 'Umbria',
	category: 2,
	icon: null,
	id: 48,
	name: 'Umbria',
	slug: 'destinazioni/umbria'
}, {
	abstract: 'Valle d\'Aosta',
	category: 2,
	icon: null,
	id: 29,
	name: 'Valle d\'Aosta',
	slug: 'destinazioni/valle-aosta'
}, {
	abstract: 'Veneto',
	category: 2,
	icon: null,
	id: 30,
	name: 'Veneto',
	slug: 'destinazioni/veneto'
}, {
	abstract: 'Egitto',
	category: 3,
	icon: null,
	id: 32,
	name: 'Egitto',
	slug: 'destinazioni/egitto'
}, {
	abstract: 'Francia',
	category: 3,
	icon: null,
	id: 49,
	name: 'Francia',
	slug: 'destinazioni/francia'
}, {
	abstract: 'Kenya',
	category: 3,
	icon: null,
	id: 51,
	name: 'Kenya',
	slug: 'destinazioni/kenya'
}, {
	abstract: 'Ungheria',
	category: 3,
	icon: null,
	id: 67,
	name: 'Ungheria',
	slug: 'destinazioni/ungheria'
}, {
	abstract: 'Mediterraneo Occidentale',
	category: 3,
	icon: null,
	id: 68,
	name: 'Mediterraneo Occidentale',
	slug: 'destinazioni/mediterraneo-occidentale'
}, {
	abstract: 'Mediterraneo Orientale',
	category: 3,
	icon: null,
	id: 69,
	name: 'Mediterraneo Orientale',
	slug: 'destinazioni/mediterraneo-orientale'
}, {
	abstract: 'Svizzera',
	category: 3,
	icon: null,
	id: 78,
	name: 'Svizzera',
	slug: ''
}, {
	abstract: '',
	category: 3,
	icon: null,
	id: 62,
	name: 'Corsica',
	slug: ''
}, {
	abstract: '',
	category: 3,
	icon: null,
	id: 59,
	name: 'Cuba',
	slug: 'destinazioni/a-cuba'
}, {
	abstract: '',
	category: 3,
	icon: null,
	id: 13,
	name: 'Austria',
	slug: 'destinazioni/austria'
}, {
	abstract: 'Croazia',
	category: 3,
	icon: null,
	id: 57,
	name: 'Croazia',
	slug: 'destinazioni/croazia'
}, {
	abstract: 'Grecia',
	category: 3,
	icon: null,
	id: 34,
	name: 'Grecia',
	slug: 'destinazioni/grecia'
}, {
	abstract: 'Messico',
	category: 3,
	icon: null,
	id: 35,
	name: 'Messico',
	slug: 'destinazioni/messico'
}, {
	abstract: 'Slovenia',
	category: 3,
	icon: null,
	id: 53,
	name: 'Slovenia',
	slug: 'destinazioni/slovenia'
}, {
	abstract: 'Spagna',
	category: 3,
	icon: null,
	id: 33,
	name: 'Spagna',
	slug: 'destinazioni/spagna'
}, {
	abstract: 'Tanzania',
	category: 3,
	icon: null,
	id: 50,
	name: 'Tanzania',
	slug: 'destinazioni/zanzibar'
}];
